### ISSUE TITLE
Recording non-localhost sites

### ISSUE THREAD

**Issue by hemaldev** [amatsuda/heavens_door#11]
This looks great, thanks for putting it together!

I haven't dived in yet, but was wondering if it'll play nicely recording non localhost sites?

Thanks again

**Comment by amatsuda** [comment]
Please just try before asking. It shouldn’t be hard.
And of course, feel free to send patches if you find any problems :)

**Comment by hemaldev** [comment]
Not had time to try, hence I thought I'd quickly ask. Sorry for the trouble. (Came across the gem in this morning's Ruby Weekly). Thanks again for the gem.
