### ISSUE TITLE
Button position for recording

### ISSUE THREAD

**Issue by luizpicolo** [amatsuda/heavens_door#5]
The button that starts burning in both Chrome and Safari browsers on the Mac is in a difficult position to click due to the scroll bar.

![screen shot 2019-02-02 at 11 58 26 am](https://user-images.githubusercontent.com/1373275/52165647-409ce800-26e2-11e9-8168-738c7f3ede00.png)

**Comment by amatsuda** [comment]
Indeed. PRs are welcome!
